version: '3.8'

services:

  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: APP
      POSTGRES_PASSWORD: APP
      POSTGRES_DB: labprog

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - ../common/backend/m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ### --- SEGUIR INSTRUCIVO AQUI ####
    #working_dir: /home/node # -- Descomentar luego de ng new
    working_dir: /home/node/app
    command: npm start
    ### ------------------------- ####
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/home/node      
    # Activar lo siguiente luego del taller End-to-end
    # depends_on: 
      # - backend
    expose:
      - 3306
      - 33060

#  testing:
#    image: node:alpine
#    container_name: testing
#    profiles:
#      - test
#    working_dir: /home/node
#    volumes:
#      - ./testing:/home/node
#      - ../common/testing/node_modules:/home/node/node_modules      
#    command: npm test
#    depends_on:
#      - backend

volumes:
  postgres:
